# 实验名称
experiment: "CAN"

# 随机种子
seed: 20211024

# 训练参数
epochs: 240
batch_size: 8
workers: 0
train_parts: 1
valid_parts: 1
valid_start: 0
save_start: 0

optimizer: Adadelta
lr: 1
lr_decay: cosine
step_ratio: 10
step_decay: 5
eps: 1e-6
weight_decay: 1e-4
beta: 0.9

dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

# 训练数据
train_image_path: 'datasets/train_images.pkl'
train_label_path: 'datasets/train_labels.txt'

eval_image_path: 'datasets/test_images.pkl'
eval_label_path: 'datasets/test_labels.txt'

word_path: 'datasets/word.txt'

# collate_fn
collate_fn: collate_fn

densenet:
  ratio: 16
  nDenseBlocks: 8
  growthRate: 8
  reduction: 0.5
  bottleneck: True
  use_dropout: True

encoder:
  input_channel: 1
  out_channel: 116

decoder:
  net: AttDecoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256

counting_decoder:
  in_channel: 116
  out_channel: 22

attention:
  attention_dim: 128
  word_conv_kernel: 1

attention_map_vis_path: 'vis/attention_map'
counting_map_vis_path: 'vis/counting_map'

whiten_type: None
max_step: 256

optimizer_save: False
finetune: False
checkpoint_dir: 'checkpoints'
#checkpoint: "checkpoints/CAN_2023-03-27-19-22_decoder-AttDecoder/CAN_2023-03-27-19-22_decoder-AttDecoder_WordRate-0.4467_ExpRate-0.0000_26.pth"
log_dir: 'logs'
